# Generated by Django 2.2 on 2021-01-04 12:06

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tweets', '0004_auto_20210104_1204'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TweetLikes',
            new_name='TweetLike',
        ),
    ]
